name: Build and Deploy Image to Develop environment

on:
 push:
    branches: [develop]
 workflow_dispatch:

env:
  IMAGE_NAME: asv-rollback-test-dev
  REPO_NAME: asv-rollback-test

jobs:
  versioning-build-deploy:
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT DEL CODICE
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---- VERSIONING ----
      - name: Get next tag version
        id: tag_version
        run: |
          last_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "Last tag: $last_tag"
          IFS='.' read -r major minor patch <<< "$last_tag"
          new_tag="$major.$minor.$((patch+1))"
          echo "new_tag=$new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      # ---- BUILD DOCKER ----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITOPS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/assolombarda-it/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}-${{ github.ref_name }}
            ghcr.io/assolombarda-it/${{ env.IMAGE_NAME }}:latest-${{ github.ref_name }}

      # ---- CONTINUOUS DEPLOYMENT (FLUXCD) ----

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: assolombarda-it/asv-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: asv-gitops
          ref: ${{ github.ref_name }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update deployment.yaml with new tag
        run: |
          new_tag=${{ steps.tag_version.outputs.new_tag }}
          DEPLOY_FILE="asv-gitops/apps/${{ env.REPO_NAME }}/deployment.yaml"
          
          sed -i "s|image: ghcr.io/assolombarda-it/${{ env.IMAGE_NAME }}:.*|image: ghcr.io/assolombarda-it/${{ env.IMAGE_NAME }}:${new_tag}-${{ github.ref_name }}|" "$DEPLOY_FILE"

          cd asv-gitops
          git add "$DEPLOY_FILE"
          git commit -m "Update ${{ env.IMAGE_NAME }} image tag to ${new_tag}-${{ github.ref_name }} [ci skip]" || echo "No changes"
          git push origin ${{ github.ref_name }}
 
